using Godot;
using Newtonsoft.Json;
using OmoriSandbox.Battle;
using OmoriSandbox.Editor;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using OmoriSandbox.Animation;
using FileAccess = Godot.FileAccess;

namespace OmoriSandbox.Modding;

internal partial class ModManager : Node
{
	public static ModManager Instance;
	private const int ACTOR_SIZE = 106;

	private readonly List<ModMetadata> LoadedMods = [];
	private readonly List<Mod> ModNodes = [];

	public override void _Ready()
	{
		Instance = this;

		if (!DirAccess.DirExistsAbsolute("user://mods"))
		{
			using DirAccess access = DirAccess.Open("user://");
			access.MakeDir("mods");
			GD.Print("Created user://mods directory");
		}

		if (!DirAccess.DirExistsAbsolute("user://mods/custom"))
		{
			using DirAccess access = DirAccess.Open("user://mods");
			access.MakeDir("custom");
			access.MakeDirRecursive("custom/battlebacks");
			access.MakeDirRecursive("custom/bgm");
			using FileAccess json = FileAccess.Open("user://mods/custom/mod.json", FileAccess.ModeFlags.Write);
			json.StoreString(JsonConvert.SerializeObject(new ModMetadata("custom", "My Custom Stuff",
				"This mod is autogenerated by OmoriSandbox to allow easy importing of custom assets.",
				"OmoriSandbox", "1.0.0", "")));

			using FileAccess readme = FileAccess.Open("user://mods/custom/README.txt", FileAccess.ModeFlags.Write);
			readme.StoreString("""
			--- This mod was auto-generated by OmoriSandbox to allow easy importing of custom BGM and Battlebacks. ---

			Simply place your custom .ogg files in the 'bgm' folder and .png/.gif files in the 'battlebacks' folder.
			If you delete the 'custom' folder OmoriSandbox will regenerate it on the next launch.
			See https://ebro912.gitbook.io/omorisandbox/modding/direct-file-modding for more information.
			""");
			GD.Print("Autogenerated default custom mod");
		}
	}

	public override void _Process(double delta)
	{
		foreach (Mod node in ModNodes)
			node.OnProcess(delta);
	}

	public override void _ExitTree()
	{
		foreach (Mod node in ModNodes)
			node.OnUnload();
	}

	public void LoadMods()
	{
		GD.Print("Beginning mod loading...");
		int processed = 0;
		int total = 0;
		Stopwatch sw = Stopwatch.StartNew();

		foreach (string dirName in DirAccess.GetDirectoriesAt("user://mods"))
		{
			if (LoadMod(dirName))
				processed++;
			total++;
		}

		sw.Stop();
		GD.Print($"Loaded {processed}/{total} mods in {sw.ElapsedMilliseconds}ms");
		MainMenuManager.Instance.UpdateModsLoaded(processed, total);
	}

	private bool LoadMod(string dirName)
	{
		if (!FileAccess.FileExists($"user://mods/{dirName}/mod.json"))
		{
			GD.PushWarning($"Missing mod.json in {dirName}, skipping!");
			return false;
		}
		using FileAccess access = FileAccess.Open($"user://mods/{dirName}/mod.json", FileAccess.ModeFlags.Read);
		if (access == null)
		{
			GD.PushError($"Failed to open mod.json from {dirName}");
			return false;
		}
		ModMetadata metadata;
		try
		{
			metadata = JsonConvert.DeserializeObject<ModMetadata>(access.GetAsText());
			if (!metadata.Validate(out string validationError))
			{
				GD.PushError($"Invalid mod.json in {dirName}: {validationError}");
				return false;
			}
			if (LoadedMods.Any(x => x.Id == metadata.Id))
			{
				GD.PushWarning($"Mod {metadata.Id} is already loaded, skipping!");
				return false;
			}
		}
		catch
		{
			GD.PushError($"Failed to read mod.json from mod {dirName}");
			return false;
		}

		ModLoadReport report = new(metadata.Name, metadata.Version);

		foreach (string modDll in DirAccess.GetFilesAt("user://mods/" + dirName).Where(x => x.EndsWith(".dll")))
		{
			if (!LoadModAssembly($"{dirName}/{modDll}"))
				return false;
		}

		foreach (string modDir in DirAccess.GetDirectoriesAt("user://mods/" + dirName))
		{
			switch (modDir.ToLower())
			{
				case "actors":      LoadActors(dirName, report); break;
				case "bgm":         LoadBGM(dirName, report); break;
				case "sfx":         LoadSFX(dirName, report); break;
				case "battlebacks": LoadBattlebacks(dirName, report); break;
				case "enemies":     LoadEnemies(dirName, report); break;
				case "animations":  LoadAnimations(dirName); break;
				case "stateicons":  LoadStateIcons(dirName, report); break;
				case "presets":     LoadPresets(dirName, report); break;
			}
		}

		Texture2D icon = null;
		if (!string.IsNullOrEmpty(metadata.Icon) && metadata.Icon.EndsWith(".png"))
		{
			if (metadata.Icon.Contains("..") || metadata.Icon.Contains("://") || Path.IsPathRooted(metadata.Icon))
			{
				report.Warn("metadata", "icon", $"Invalid icon path '{metadata.Icon}' (path traversal not allowed)");
			}
			else
			{
				Image iconImage = Image.LoadFromFile($"user://mods/{dirName}/{metadata.Icon}");
				if (iconImage != null)
					icon = ImageTexture.CreateFromImage(iconImage);
				else
					report.Warn("metadata", "icon", $"Failed to load icon: {metadata.Icon}");
			}
		}

		report.PrintSummary();
		MainMenuManager.Instance.AddModListEntry(metadata, icon);
		LoadedMods.Add(metadata);
		return true;
	}

	private bool LoadModAssembly(string path)
	{
		try
		{
			AssemblyLoadContext context = AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
			if (context == null)
				return false;
			Assembly asm = context.LoadFromAssemblyPath(ProjectSettings.GlobalizePath("user://mods/" + path));
			var type = asm.GetTypes().FirstOrDefault(t => t.IsSubclassOf(typeof(Mod)) && !t.IsAbstract);
			if (type == null)
			{
				GD.PushWarning($"No valid Mod class found in assembly {path}, skipping!");
				return false;
			}

			if (Activator.CreateInstance(type) is not Mod instance)
			{
				GD.PrintErr("Failed to instantiate Mod class from assembly " + path);
				return false;
			}

			AddChild(instance);
			ModNodes.Add(instance);
			instance.OnLoad();

			return true;
		}
		catch (Exception ex)
		{
			GD.PrintErr("Failed to load assembly " + path + ": " + ex);
			return false;
		}
	}

	private void LoadPresets(string root, ModLoadReport report)
	{
		string path = "user://mods/" + root + "/presets";
		foreach (string preset in DirAccess.GetFilesAt(path))
		{
			if (!preset.EndsWith(".json"))
			{
				report.Error("presets", preset, "File is not JSON");
				report.CountSkipped();
				continue;
			}
			
			PresetManager.Instance.LoadModdedPreset(path + "/" + preset, report);
		}
	}

	private void LoadActors(string root, ModLoadReport report)
	{
		string path = "user://mods/" + root + "/actors";
		foreach (string actor in DirAccess.GetDirectoriesAt(path))
		{
			try
			{
				string[] files = DirAccess.GetFilesAt($"{path}/{actor}");
				string json = files.FirstOrDefault(x => x.EndsWith(".json"));
				if (json == null)
				{
					report.Error("actors", actor, "Missing JSON file");
					report.CountSkipped();
					continue;
				}
				using FileAccess access = FileAccess.Open($"{path}/{actor}/{json}", FileAccess.ModeFlags.Read);
				if (access == null)
				{
					report.Error("actors", actor, $"Failed to open {json}");
					report.CountSkipped();
					continue;
				}
				JsonActorMod mod = JsonConvert.DeserializeObject<JsonActorMod>(access.GetAsText());
				if (!mod.Validate(report))
				{
					report.CountSkipped();
					continue;
				}
				SpriteFrames frames = BuildActorAnimation(mod, $"{path}/{actor}", report);
				Database.RegisterJsonPartyMember(mod, frames);
				report.CountLoaded();
			}
			catch (Exception e)
			{
				report.Error("actors", actor, $"Failed to load: {e.Message}");
				report.CountSkipped();
			}
		}
	}

	private SpriteFrames BuildActorAnimation(JsonActorMod jsonActor, string path, ModLoadReport report)
	{
		if (!FileAccess.FileExists($"{path}/{jsonActor.Atlas}"))
		{
			report.Error("actors", jsonActor.Name, $"Atlas file not found: {jsonActor.Atlas}");
			return null;
		}
		Image image = Image.LoadFromFile($"{path}/{jsonActor.Atlas}");
		if (image == null)
		{
			report.Error("actors", jsonActor.Name, $"Failed to load atlas image: {jsonActor.Atlas}");
			return null;
		}
		Texture2D texture = ImageTexture.CreateFromImage(image);
		int columns = texture.GetWidth() / ACTOR_SIZE;
		if (columns == 0)
		{
			report.Error("actors", jsonActor.Name, $"Atlas is too small (width {texture.GetWidth()}px < {ACTOR_SIZE}px)");
			return null;
		}
		SpriteFrames spriteFrames = new();
		foreach (JsonModAnimationData data in jsonActor.Animation)
		{
			spriteFrames.AddAnimation(data.Emotion);
			spriteFrames.SetAnimationSpeed(data.Emotion, data.Fps);
			spriteFrames.SetAnimationLoop(data.Emotion, true);
			foreach (int idx in data.Frames)
			{
				int column = idx % columns;
				int row = idx / columns;
				AtlasTexture tex = new()
				{
					Atlas = texture,
					Region = new Rect2(column * ACTOR_SIZE, row * ACTOR_SIZE, ACTOR_SIZE, ACTOR_SIZE)
				};
				spriteFrames.AddFrame(data.Emotion, tex);
			}
		}
		return spriteFrames;
	}

	private void LoadEnemies(string root, ModLoadReport report)
	{
		string path = "user://mods/" + root + "/enemies";
		foreach (string enemy in DirAccess.GetDirectoriesAt(path))
		{
			try
			{
				string[] files = DirAccess.GetFilesAt($"{path}/{enemy}");
				string json = files.FirstOrDefault(x => x.EndsWith(".json"));
				if (json == null)
				{
					report.Error("enemies", enemy, "Missing JSON file");
					report.CountSkipped();
					continue;
				}
				using FileAccess access = FileAccess.Open($"{path}/{enemy}/{json}", FileAccess.ModeFlags.Read);
				if (access == null)
				{
					report.Error("enemies", enemy, $"Failed to open {json}");
					report.CountSkipped();
					continue;
				}
				JsonEnemyMod mod = JsonConvert.DeserializeObject<JsonEnemyMod>(access.GetAsText());
				if (!mod.Validate(report))
				{
					report.CountSkipped();
					continue;
				}
				SpriteFrames frames = BuildEnemyAnimation(mod, $"{path}/{enemy}", report);
				Database.RegisterJsonEnemy(mod, frames);
				report.CountLoaded();
			}
			catch (Exception e)
			{
				report.Error("enemies", enemy, $"Failed to load: {e.Message}");
				report.CountSkipped();
			}
		}
	}

	private SpriteFrames BuildEnemyAnimation(JsonEnemyMod jsonEnemy, string path, ModLoadReport report)
	{
		if (!FileAccess.FileExists($"{path}/{jsonEnemy.Atlas}"))
		{
			report.Error("enemies", jsonEnemy.Name, $"Atlas file not found: {jsonEnemy.Atlas}");
			return null;
		}
		Image image = Image.LoadFromFile($"{path}/{jsonEnemy.Atlas}");
		if (image == null)
		{
			report.Error("enemies", jsonEnemy.Name, $"Failed to load atlas image: {jsonEnemy.Atlas}");
			return null;
		}
		Texture2D texture = ImageTexture.CreateFromImage(image);
		int width = jsonEnemy.Width;
		int height = jsonEnemy.Height;
		if (width > texture.GetWidth() || height > texture.GetHeight())
		{
			report.Error("enemies", jsonEnemy.Name, $"Atlas dimensions ({texture.GetWidth()}x{texture.GetHeight()}) smaller than frame size ({width}x{height})");
			return null;
		}
		int columns = texture.GetWidth() / width;
		SpriteFrames spriteFrames = new();
		foreach (JsonModAnimationData data in jsonEnemy.Animation)
		{
			spriteFrames.AddAnimation(data.Emotion);
			spriteFrames.SetAnimationSpeed(data.Emotion, data.Fps);
			spriteFrames.SetAnimationLoop(data.Emotion, true);
			foreach (int idx in data.Frames)
			{
				int column = idx % columns;
				int row = idx / columns;
				AtlasTexture tex = new()
				{
					Atlas = texture,
					Region = new Rect2(column * width, row * height, width, height)
				};
				spriteFrames.AddFrame(data.Emotion, tex);
			}
		}
		return spriteFrames;
	}

	private void LoadBGM(string root, ModLoadReport report)
	{
		string path = "user://mods/" + root + "/bgm";
		foreach (string file in DirAccess.GetFilesAt(path))
		{
			if (file.EndsWith(".ogg"))
			{
				if (!AudioManager.Instance.LoadCustomBGM($"{path}/{file}"))
				{
					report.Error("bgm", file, "Failed to load custom BGM");
					report.CountSkipped();
				}
				else
				{
					report.CountLoaded();
				}
			}
		}
	}


	private void LoadSFX(string root, ModLoadReport report)
	{
		string path = "user://mods/" + root + "/sfx";
		foreach (string file in DirAccess.GetFilesAt(path))
		{
			if (file.EndsWith(".ogg"))
			{
				if (!AudioManager.Instance.LoadCustomSFX($"{path}/{file}"))
				{
					report.Error("sfx", file, "Failed to load custom SFX");
					report.CountSkipped();
				}
				else
				{
					report.CountLoaded();
				}
			}
		}
	}

	private void LoadBattlebacks(string root, ModLoadReport report)
	{
		string path = "user://mods/" + root + "/battlebacks";
		foreach (string file in DirAccess.GetFilesAt(path))
		{
			try
			{
				BattlebackManager.Instance.AddBattleback("user://mods/" + root + "/battlebacks/" + file);
				report.CountLoaded();
			}
			catch (Exception e)
			{
				report.Error("battlebacks", file, $"Failed to load: {e.Message}");
				report.CountSkipped();
			}
		}
	}

	private void LoadAnimations(string root)
	{
		string path = "user://mods/" + root + "/animations";
		if (FileAccess.FileExists(path + "/Animations.json"))
			AnimationManager.Instance.LoadModded(root);
		if (FileAccess.FileExists(path + "/Animations.jsond"))
			AnimationManager.Instance.LoadDeltaPatch(root);
	}

	private void LoadStateIcons(string root, ModLoadReport report)
	{
		string path = "user://mods/" + root + "/stateicons";
		foreach (string file in DirAccess.GetFilesAt(path))
		{
			if (file.EndsWith(".png"))
			{
				Image image = Image.LoadFromFile(path + "/" + file);
				if (image == null)
				{
					report.Warn("stateicons", file, "Failed to load image");
					report.CountSkipped();
					continue;
				}
				Texture2D texture = ImageTexture.CreateFromImage(image);
				Database.AddStateIcon(file.GetBaseName(), texture);
				report.CountLoaded();
			}
		}
	}
}
